cf:
  butlers:
    demo: localhost:8080
   # dhaka: cf-butler-responsible-bat-dl.apps.dhaka.cf-app.com
  sslValidationSkipped: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  cloud:
    config:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    config:
      enabled: true
